### ISSUE TITLE
Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

### ISSUE THREAD

**Issue by shakibHossain** [ai2010/machine_learning_for_the_web#4]
TypeError at /movies-recs/
Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/movies-recs/
Django Version:	1.11.28
Exception Type:	TypeError
Exception Value:	
Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'
Exception Location:	/home/shakib/Documents/winter2020/cs872/project-final/movie_recommendation_app/rec_app/management/commands/load_data.py in GetRecItems, line 255
Python Executable:	/usr/bin/python
Python Version:	2.7.17
Python Path:	
['/home/shakib/Documents/winter2020/cs872/project-final/movie_recommendation_app',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/home/shakib/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/gtk-2.0']
Server time:	Wed, 11 Mar 2020 18:11:01 +0000

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/movies-recs/

Django Version: 1.11.28
Python Version: 2.7.17
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'rest_framework_swagger',
 'rec_app']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/home/shakib/.local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/shakib/.local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/shakib/.local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/shakib/Documents/winter2020/cs872/project-final/movie_recommendation_app/rec_app/views.py" in movies_recs
  271.         u_rec = llr.GetRecItems(u_vec,True)

File "/home/shakib/Documents/winter2020/cs872/project-final/movie_recommendation_app/rec_app/management/commands/load_data.py" in GetRecItems
  248.         items_weight = np.dot(u_vec,self.items_llr)

Exception Type: TypeError at /movies-recs/
Exception Value: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

**Comment by ai2010** [comment]
An operation (comparison) between a float value dtype('float64')  and a unicode string    dtype('<U32')  would evoke such an error, which is what happened in this case. Instead operation should be between variables with same data types to avoid such errors. 
Specifically change:
chapter_7/server_movierecsys/books_recsys_app/views.py: 
          In line 248 replace np.array with literal_eval()
	“u_vec = literal_eval(userprofile.array)”
chapter_7/server_movierecsys/books_recsys_app/models.py:
	In line 24: replace None with 0:
         “elif len(recsvec)!=None:”
